
export const metadata = {
  title: "SLEW",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children
}) {
  return (
    <div className="auth-container w-full h-dvh bg-[#F5F5F5]">
      {children}
    </div>
  );
}
